pipeline {
    agent any
    
    stages {
            stage('Compile and Clean') { 
                steps {
                       bat 'mvn compile'
                      }
            }
       
	        stage('Junit5 Test') { 
                 steps {
	                bat 'mvn test'
                  }
            }

	    stage('Jacoco Coverage Report') {
        	     steps{
            		//jacoco()
            		echo 'TestCoverage'
		          }
	        }
		stage('SonarQube'){
			steps{
			//	bat label: '', script: '''mvn sonar:sonar \
			//	-Dsonar.host.url=http://CDLVDIDEVMAN500:9000 \
			//	-Dsonar.login=c0909bf6713cd534393d47364d1da553431a220d'''
			echo 'Sonar Code Scanning '
				}	
   			}
        stage('Maven Build') { 
            steps {
                bat 'mvn clean install'
                  }
            }
        stage('Build Docker image'){
           steps {
                   	    bat 'docker build -t  sampleproject --build-arg VER=1.0 .'
		         }
             }
        stage('Docker Login'){
            steps {
              echo "docker login from console"
            }                
        }
        stage('Docker Push'){
            steps {
                bat 'docker push aruna708/sampleproject'
            }
        }
        stage('Docker deploy'){
            steps {
                bat 'docker run -itd -p  8086:8086 sampleproject'
             }
        }
    
     
    }
}
